/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-secondary-container": "#007165",
        "surface-container": "#eceef3",
        "tertiary-fixed-dim": "#ffb2bd",
        "on-tertiary-container": "#fffbff",
        "background": "#f8f9ff",
        "on-error-container": "#93000a",
        "outline": "#787585",
        "secondary": "#006b5f",
        "surface": "#f8f9ff",
        "tertiary": "#993c50",
        "on-surface-variant": "#474554",
        "secondary-fixed": "#62fae3",
        "error-container": "#ffdad6",
        "tertiary-container": "#b85468",
        "surface-container-high": "#e7e8ee",
        "on-tertiary-fixed-variant": "#7e273c",
        "on-background": "#191c20",
        "on-error": "#ffffff",
        "on-tertiary": "#ffffff",
        "primary-fixed": "#e5deff",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f2f3f9",
        "primary": "#5a45cb",
        "secondary-container": "#62fae3",
        "inverse-on-surface": "#eff0f6",
        "on-secondary-fixed": "#00201c",
        "primary-fixed-dim": "#c8bfff",
        "on-primary-container": "#fffbff",
        "surface-variant": "#e1e2e8",
        "primary-container": "#7360e5",
        "on-secondary": "#ffffff",
        "on-primary": "#ffffff",
        "error": "#ba1a1a",
        "surface-tint": "#5c47cd",
        "surface-container-highest": "#e1e2e8",
        "on-secondary-fixed-variant": "#005047",
        "inverse-primary": "#c8bfff",
        "on-primary-fixed": "#190064",
        "secondary-fixed-dim": "#3bddc7",
        "on-tertiary-fixed": "#400013",
        "surface-dim": "#d8dae0",
        "on-primary-fixed-variant": "#442bb5",
        "on-surface": "#191c20",
        "surface-bright": "#f8f9ff",
        "inverse-surface": "#2e3135",
        "tertiary-fixed": "#ffd9dd",
        "outline-variant": "#c9c4d6"
      },
      fontFamily: {
        "headline": ["Plus Jakarta Sans"],
        "body": ["Manrope"],
        "label": ["Manrope"]
      },
      borderRadius: {
        "DEFAULT": "1rem", 
        "lg": "2rem", 
        "xl": "3rem", 
        "full": "9999px"
      },
    },
  },
  plugins: [],
}
